name = "docs-relational-migrator"
title = "Relational Migrator"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]
toc_landing_pages = [
"/installation",
"/code-generation",
"/code-generation/download-all-code-files",
"/code-generation/download-single-code-files"
]

# [constants]
# constant = "value"
