name = "docs-relational-migrator"
title = "Relational Migrator"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/atlas/app-services/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

toc_landing_pages = [
"supported-databases",
"installation",
"installation/install-on-a-local-machine/install-on-a-local-machine",
"installation/install-on-an-unattended-server/install-on-an-unattended-server",
"installation/install-on-an-unattended-server/debian-server-installation/debian-server-installation",
"installation/install-on-an-unattended-server/windows-server-installation/windows-server-installation",
"installation/install-on-an-unattended-server/rhel-centos-server-installation/rhel-centos-server-installation",
"installation/kafka-deployments/migrator-with-kafka",
"installation/file-location",
"projects/projects",
"mapping-rules/mapping-rules",
"mapping-rules/mapping-rule-options/mapping-rule-options",
"mapping-rules/fields/calculated-fields/calculated-fields",
"mapping-rules/fields/field-customizations",
"mapping-rules/synthetic-foreign-key/synthetic-foreign-keys",
"table-filters/table-filters",
"diagrams/diagrams",
"diagrams/navigate-diagrams/navigate-diagrams",
"diagrams/navigate-diagrams/working-with-entities/working-with-entities",
"jobs/sync-jobs",
"jobs/data-verification/data-verification",
"connection-strings/connection-strings",
"code-generation",
"code-generation/generate-app-code",
"code-generation/query-converter",
"diagrams/manage-diagrams",
"getting-started",
"jobs/prerequisites",
"api-docs",
"deployment-considerations",
"code-generation/query-converter-test-queries"
]

[constants]
ddl = ":abbr:`DDL (Data Definition Language)`"
job = "sync job" #this will be updated to migration job in the near future.
job_plural = "sync jobs" #this will be updated to migration jobs in the near future.
migrator-api = "REST API Documentation"
migrator-api-endpoints = "Endpoints"
