name = "docs-relational-migrator"
title = "Relational Migrator"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

toc_landing_pages = [
"/installation/install-on-an-unattended-server",
"/installation/install-on-an-unattended-server/debian-server-installation",
"/installation/install-on-an-unattended-server/windows-server-installation",
"/installation/install-on-an-unattended-server/rhel-centos-server-installation"
]

# [constants]
# constant = "value"
