name = "docs-relational-migrator"
title = "Relational Migrator"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

toc_landing_pages = [
"/installation/install-on-an-unattended-server",
"/installation/install-on-an-unattended-server/install-windows-server",
"/installation/install-on-an-unattended-server/install-debian-server",
"/installation/install-on-an-unattended-server/install-rhel-server",
"/installation/install-on-an-unattended-server/windows-system-service",
"/installation/install-on-an-unattended-server/debian-system-service",
"/installation/install-on-an-unattended-server/rhel-system-service",
"/installation/install-on-an-unattended-server/windows-external-access"
]

# [constants]
# constant = "value"
